on:
  push:
    branches: ["master"]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./build

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  idk:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: 20
          # Java distribution. See the list of supported distributions in README file
          distribution: oracle
          # The package type (jdk, jre, jdk+fx, jre+fx)
          java-package: jdk
      - name: Check out
        uses: actions/checkout@v4.2.2
      - name: Build
        run: bash compile.sh
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: build/
      - name: Deploy to GitHub pages
        uses: actions/deploy-pages@v4.0.5
